# Generated by Django 3.1.6 on 2021-02-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20210222_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
